# Generated by Django 4.1.1 on 2022-09-21 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='recipe',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='recipe',
            field=models.ManyToManyField(blank=True, null=True, related_name='ingredients', to='api.recipe', verbose_name='Рецепты'),
        ),
    ]
