# Generated by Django 4.1.1 on 2022-09-21 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_ingredient_recipe_ingredientsinrecipe'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredientsinrecipe',
            options={'verbose_name': 'ингредиент в рецепте', 'verbose_name_plural': 'ингредиенты в рецепте'},
        ),
        migrations.AlterModelTable(
            name='ingredientsinrecipe',
            table='ingredients_in_recipe',
        ),
    ]
