# Generated by Django 4.1.1 on 2022-09-21 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_ingredientsinrecipe_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favourites',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourites_in', to='api.recipe', verbose_name='рецепты'),
        ),
    ]
