# Generated by Django 4.1.1 on 2022-09-21 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_favourites_recipe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favourites',
            name='recipe',
        ),
        migrations.AddField(
            model_name='recipe',
            name='favourite_in',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='api.favourites', verbose_name='В избранном'),
        ),
    ]
