# Generated by Django 4.1.1 on 2022-09-21 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_recipe_favourite_in_recipe_favourite_in'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favourites',
            options={'verbose_name': 'избранное', 'verbose_name_plural': 'избранные'},
        ),
        migrations.AddField(
            model_name='recipe',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipes', to='api.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='favourite_in',
            field=models.ManyToManyField(blank=True, related_name='recipes', to='api.favourites', verbose_name='В избранном'),
        ),
        migrations.AlterModelTable(
            name='favourites',
            table='favourites',
        ),
    ]
