# Generated by Django 4.1.1 on 2022-09-27 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_category_id_alter_favourites_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dislike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dislikes', to='api.user')),
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='dislike',
            field=models.ManyToManyField(blank=True, related_name='recipes', to='api.dislike', verbose_name='Дизлайкнули'),
        ),
    ]
